#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export GIN_MODE=test
export RISE_ENV=test

if [[ ! -z $(docker images -q quay.io/nitrous/pubstorm-optimizer:latest) ]]; then
  echo 'Using quay.io/nitrous/pubstorm-optimizer:latest image that exists locally.'
  echo 'You might need to update it by running `docker pull quay.io/nitrous/pubstorm-optimizer:latest` if any builder/optimizer-related tests fail unexpectedly.'
fi

$DIR/env ginkgo -r "$@"
